### ISSUE TITLE
Error when using blocksToMarkdownLossy and blocksToHTMLLossy

### ISSUE THREAD

**Issue by phanminhtai** [defensestation/blocknote-code#1]

**Comment by gsingh-ds** [comment]
@phanminhtai working on it

**Comment by phanminhtai** [comment]
I still get the error when using version 1.0.4
![image](https://github.com/defensestation/blocknote-code/assets/53898609/898959d8-e045-43bd-8b2f-05859ebb214f)
![image](https://github.com/defensestation/blocknote-code/assets/53898609/fbebfc5e-9cca-4d60-9f0e-318323272409)
![image](https://github.com/defensestation/blocknote-code/assets/53898609/1ed443ed-2423-49a7-acf3-01ed26798af6)

**Comment by hsingh-ds** [comment]
@phanminhtai Could you please share the snippet of code that's throwing the error?

**Comment by hsingh-ds** [comment]
@phanminhtai Can you put it on sandbox?

**Comment by phanminhtai** [comment]
@hsingh-ds here bro: https://codesandbox.io/p/devbox/jhpyw3

**Comment by hsingh-ds** [comment]
@phanminhtai I've made some adjustments to the code you provided. It appears that the issue arises from performing the conversion operation from useEffect.

To address this, I've updated the code. You can take a look at the changes via the provided link [here](https://codesandbox.io/p/devbox/blocknote-forked-k276zq?file=%2Fsrc%2Feditor.tsx%3A15%2C70&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvmihd5e00082v6ejydzczzq%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvmihd5e00022v6e4odmb1yd%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvmihd5e00052v6eezix952t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvmihd5e00072v6eejda6o8q%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvmihd5e00022v6e4odmb1yd%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvmihd5d00012v6e59xutt77%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvmne85h00022v6eiac8qbw6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A70%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A70%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Feditor.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvmihd5e00022v6e4odmb1yd%2522%252C%2522activeTabId%2522%253A%2522clvmne85h00022v6eiac8qbw6%2522%257D%252C%2522clvmihd5e00072v6eejda6o8q%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvmihd5e00062v6en1zh1kdr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvmihd5e00072v6eejda6o8q%2522%252C%2522activeTabId%2522%253A%2522clvmihd5e00062v6en1zh1kdr%2522%257D%252C%2522clvmihd5e00052v6eezix952t%2522%253A%257B%2522id%2522%253A%2522clvmihd5e00052v6eezix952t%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvmihd5e00032v6efm788879%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%257D%252C%257B%2522id%2522%253A%2522clvmihd5e00042v6e47j3thys%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clvlvitbt000bdif839vhe17c%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clvmihd5e00032v6efm788879%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D). Please give it a try and let me know if it resolves the issue on your end.

**Comment by phanminhtai** [comment]
@hsingh-ds nice. Thanks!
